<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IACUTLP" failures="1" tests="5" name="Test" time="215.211" errors="0" timestamp="2023-05-04T17:08:33 PDT">
  <testcase classname="com.dsalgo.qa.testcase.SignInPageTest" name="ClickRegisterLnkSignInPageValidationTest" time="5.498"/>
  <testcase classname="com.dsalgo.qa.testcase.SignInPageTest" name="ClickSignoutLnkValidationTest" time="5.13"/>
  <testcase classname="com.dsalgo.qa.testcase.SignInPageTest" name="LoginUserwithValidCredentialsValidationTest" time="3.465"/>
  <testcase classname="com.dsalgo.qa.testcase.SignInPageTest" name="VerifyUserLogin" time="0.292">
    <failure type="java.lang.AssertionError" message="expected [https://dsportalapp.herokuapp.com/logins] but found [https://dsportalapp.herokuapp.com/login]">
      <![CDATA[java.lang.AssertionError: expected [https://dsportalapp.herokuapp.com/logins] but found [https://dsportalapp.herokuapp.com/login]
at com.dsalgo.qa.testcase.SignInPageTest.VerifyUserLogin(SignInPageTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyUserLogin -->
  <testcase classname="com.dsalgo.qa.testcase.SignInPageTest" name="LoginUserWithInvalidCredentialsValidationTest" time="3.239"/>
</testsuite> <!-- Test -->
